[version]
required-game-version = "1.1.3"
plugin-version = "2026.4.17"

[version-hash]
"1.1.3" = "78b581116dfa325eb3c9bf35ffd47660"

[replace]
"res://.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.md5" = ".import/Combat.png-88ad49c2809e77384a81bc33d532ba51.md5"
"res://.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.stex" = ".import/Combat.png-88ad49c2809e77384a81bc33d532ba51.stex"
"res://.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.md5" = ".import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.md5"
"res://.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.stex" = ".import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.stex"
"res://.import/NormalizeOrientation.png-0a6dd0a60a656a2cadca30af5cee3752.md5" = ".import/NormalizeOrientation.png-0a6dd0a60a656a2cadca30af5cee3752.md5"
"res://.import/NormalizeOrientation.png-0a6dd0a60a656a2cadca30af5cee3752.stex" = ".import/NormalizeOrientation.png-0a6dd0a60a656a2cadca30af5cee3752.stex"
"res://Assets/Combat.png" = "Assets/Combat.png"
"res://Assets/Combat.png.import" = "Assets/Combat.png.import"
"res://Assets/Copy.png" = "Assets/Copy.png"
"res://Assets/Copy.png.import" = "Assets/Copy.png.import"
"res://Assets/NormalizeOrientation.png" = "Assets/NormalizeOrientation.png"
"res://Assets/NormalizeOrientation.png.import" = "Assets/NormalizeOrientation.png.import"
"res://Core/Game.gd.remap" = "Core/Game.gd.remap"
"res://Core/Game.gde" = "Core/Game.gde"
"res://Core/Inventory.gd.remap" = "Core/Inventory.gd.remap"
"res://Core/Inventory.gde" = "Core/Inventory.gde"
"res://Core/Main.tscn" = "Core/Main.tscn"
"res://Core/RunDatabase.gd.remap" = "Core/RunDatabase.gd.remap"
"res://Core/RunDatabase.gde" = "Core/RunDatabase.gde"
"res://Core/Shop.gd.remap" = "Core/Shop.gd.remap"
"res://Core/Shop.gde" = "Core/Shop.gde"
"res://Interface/BuildHistory/BuildEntry.gd.remap" = "Interface/BuildHistory/BuildEntry.gd.remap"
"res://Interface/BuildHistory/BuildEntry.gde" = "Interface/BuildHistory/BuildEntry.gde"
"res://Interface/BuildHistory/BuildEntryPlaceholder.gd.remap" = "Interface/BuildHistory/BuildEntryPlaceholder.gd.remap"
"res://Interface/BuildHistory/BuildEntryPlaceholder.gde" = "Interface/BuildHistory/BuildEntryPlaceholder.gde"
"res://Interface/BuildHistory/BuildHistory.gd.remap" = "Interface/BuildHistory/BuildHistory.gd.remap"
"res://Interface/BuildHistory/BuildHistory.gde" = "Interface/BuildHistory/BuildHistory.gde"
"res://Interface/BuildHistory/BuildHistory.tscn" = "Interface/BuildHistory/BuildHistory.tscn"
"res://Interface/BuildHistory/OpponentPoolAdapter.gd.remap" = "Interface/BuildHistory/OpponentPoolAdapter.gd.remap"
"res://Interface/BuildHistory/OpponentPoolAdapter.gde" = "Interface/BuildHistory/OpponentPoolAdapter.gde"
"res://Interface/BuildHistory/RoundResultButton.gd.remap" = "Interface/BuildHistory/RoundResultButton.gd.remap"
"res://Interface/BuildHistory/RoundResultButton.gde" = "Interface/BuildHistory/RoundResultButton.gde"
"res://Interface/FocusGrabbingTextureButton.gd.remap" = "Interface/FocusGrabbingTextureButton.gd.remap"
"res://Interface/FocusGrabbingTextureButton.gde" = "Interface/FocusGrabbingTextureButton.gde"
"res://Interface/Lobbies/CustomUnrankedUI.gd.remap" = "Interface/Lobbies/CustomUnrankedUI.gd.remap"
"res://Interface/Lobbies/CustomUnrankedUI.gde" = "Interface/Lobbies/CustomUnrankedUI.gde"
"res://Interface/Lobbies/OtherModesUI.tscn" = "Interface/Lobbies/OtherModesUI.tscn"
"res://Interface/OpponentRankDisplay.gd.remap" = "Interface/OpponentRankDisplay.gd.remap"
"res://Interface/OpponentRankDisplay.gde" = "Interface/OpponentRankDisplay.gde"
"res://Interface/OpponentRankDisplay.tscn" = "Interface/OpponentRankDisplay.tscn"
"res://Interface/PatchNotes.gd.remap" = "Interface/PatchNotes.gd.remap"
"res://Interface/PatchNotes.gde" = "Interface/PatchNotes.gde"
"res://Interface/PatchNotes.tscn" = "Interface/PatchNotes.tscn"
"res://Interface/RarityHint.gd.remap" = "Interface/RarityHint.gd.remap"
"res://Interface/RarityHint.gde" = "Interface/RarityHint.gde"
"res://Interface/ShopRarityChart.gd.remap" = "Interface/ShopRarityChart.gd.remap"
"res://Interface/ShopRarityChart.gde" = "Interface/ShopRarityChart.gde"
"res://Interface/ShopToolbar.gd.remap" = "Interface/ShopToolbar.gd.remap"
"res://Interface/ShopToolbar.gde" = "Interface/ShopToolbar.gde"
"res://Interface/Tooltips/ItemTooltip.gd.remap" = "Interface/Tooltips/ItemTooltip.gd.remap"
"res://Interface/Tooltips/ItemTooltip.gde" = "Interface/Tooltips/ItemTooltip.gde"
"res://Items/Item.gd.remap" = "Items/Item.gd.remap"
"res://Items/Item.gde" = "Items/Item.gde"
"res://Utility/BuildHistoryDB.gd.remap" = "Utility/BuildHistoryDB.gd.remap"
"res://Utility/BuildHistoryDB.gde" = "Utility/BuildHistoryDB.gde"
"res://Utility/CustomRules.gd.remap" = "Utility/CustomRules.gd.remap"
"res://Utility/CustomRules.gde" = "Utility/CustomRules.gde"
